### ISSUE TITLE
WIFI is not stable after enabling loadable module support

### ISSUE THREAD

**Issue by meng72** [nathanchance/wahoo#8] opened 2018-08-19 02:59 UTC
First, truly thanks for the awesome work!

With flash_defconfig, after enabling loadable module support, `CONFIG_MODULES=y`, pixel 2 cannot keep the stable connection with WiFi. But if I disable this support, WiFi works as normal.

It seems that CONFIG_MODULES might conflict with WiFi somehow. Could you pls check and give any hints about how to fix it? Thanks in advance.

Attached is the dmesg. Hope it may help.

[ 1753.756260] icnss: WLAN FW is ready: 0xf8f
[ 1753.761406] R0: [kworker/u16:0][33943343001] [22:55:27.812741]  wlan: [6:I :QDF] Allowing SSR/Driver unload for wlan_hdd_shutdown
[ 1753.761540] R0: [kworker/u16:0][33943345596] [22:55:27.812877]  wlan: [6:I :HDD] hdd_wlan_shutdown: 1434: WLAN driver shutting down!
[ 1753.761665] R0: [kworker/u16:0][33943347998] [22:55:27.813002]  wlan: [6:I :HDD] hdd_reset_all_adapters: 4833: Disabling queues
[ 1753.761733] R0: [kworker/u16:0][33943349308] [22:55:27.813070]  wlan: [6:E :QDF] cds_dump_current_concurrency: 3332: unexpected num_connections value 0
[ 1753.761754] R0: [kworker/u16:0][33943349716] [22:55:27.813091]  wlan: [6:E :QDF] cds_current_concurrency_is_mcc: 2155: unexpected num_connections value 0
[ 1753.761786] R0: [kworker/u16:0][33943350318] [22:55:27.813123]  wlan: [6:E :QDF] cds_need_opportunistic_upgrade: 4057: driver isn't dbs capable, no further action needed
[ 1753.761813] R0: [kworker/u16:0][33943350862] [22:55:27.813151]  wlan: [6:I :HDD] hdd_reset_all_adapters: 4833: Disabling queues
[ 1753.761835] R0: [kworker/u16:0][33943351263] [22:55:27.813172]  wlan: [6:E :QDF] cds_convert_device_mode_to_qdf_type: 8983: Unsupported mode (7)
[ 1753.761854] R0: [kworker/u16:0][33943351627] [22:55:27.813191]  wlan: [6:E :QDF] cds_convert_device_mode_to_qdf_type: 8983: Unsupported mode (7)
[ 1753.761873] R0: [kworker/u16:0][33943351989] [22:55:27.813210]  wlan: [6:E :QDF] cds_decr_active_session: 4257: No connection with mode:5 vdev_id:1
[ 1753.761892] R0: [kworker/u16:0][33943352358] [22:55:27.813229]  wlan: [6:E :QDF] cds_decr_session_set_pcl: 4185: Invalid active session
[ 1753.762106] R0: [kworker/u16:0][33943356452] [22:55:27.813442]  wlan: [6:F :HDD] hdd_wlan_stop_modules: 10388: stop WLAN module: entering driver status=2
[ 1753.762127] R0: [kworker/u16:0][33943356867] [22:55:27.813464]  wlan: [6:I :HDD] hdd_wlan_stop_modules: 10420: Present Driver Status: 2
[ 1753.762147] R0: [kworker/u16:0][33943357258] [22:55:27.813484]  wlan: [6:I :HDD] hdd_wlan_stop_modules: 10433: Wlan transition (OPENED <- ENABLED)
[ 1753.762738] R0: [cds_mc_thread][33943368581] [22:55:27.814074]  wlan: [1764:I :SYS] Processing SYS MC STOP
[ 1753.762818] R0: [cds_mc_thread][33943370135] [22:55:27.814155]  wlan: [1764:W :SME] csr_abort_command: 1523: csr_abort_command callback scan requester
[ 1753.762860] R0: [cds_mc_thread][33943370947] [22:55:27.814197]  wlan: [1764:E :HDD] hdd_cfg80211_scan_done_callback: 1475: Dequeue of scan request failed ID: 40963
[ 1753.768479] R0: [kworker/u16:0][33943478763] [22:55:27.819812]  wlan: [6:I :HDD] hdd_ipa_uc_ol_deinit:3392: Disconnect TX PIPE tx_pipe_handle=0x19
[ 1753.771467] R0: [kworker/u16:0][33943536141] [22:55:27.822801]  wlan: [6:I :HDD] hdd_ipa_uc_ol_deinit:3396: Disconnect RX PIPE rx_pipe_handle=0xa
[ 1753.777599] R0: [kworker/u16:0][33943653883] [22:55:27.828933]  wlan: [6:I :WMI] WMI Stop\x0a
[ 1753.788678] R0: [kworker/u16:0][33943866661] [22:55:27.840015]  wlan: [6:I :TRX] Global Pool
[ 1753.789125] R0: [kworker/u16:0][33943875268] [22:55:27.840464]  wlan: [6:I :TRX] freed 6 tx frames for which no resp from target
[ 1753.789140] R0: [kworker/u16:0][33943875583] [22:55:27.840480]  wlan: [6:I :TRX] ol_tx_deregister_flow_control: 130: flow pool list is not empty 0!!!\x0a
[ 1753.789154] R0: [kworker/u16:0][33943875852] [22:55:27.840494]  wlan: [6:I :TRX] Global Pool
[ 1753.807898] R0: [cds_mc_thread][33944235658] [22:55:27.859234]  wlan: [1764:I :QDF] cds_mc_thread: MC thread signaled to shutdown
[ 1753.807915] R0: [cds_mc_thread][33944236081] [22:55:27.859256]  wlan: [1764:I :QDF] cds_mc_thread: MC Thread exiting!!!!
[ 1753.807995] R0: [cds_ol_rx_threa][33944237602] [22:55:27.859335]  wlan: [1765:I :QDF] cds_ol_rx_thread: Shutting down OL RX Thread
[ 1753.811192] R0: [kworker/u16:0][33944298987] [22:55:27.862532]  wlan: [6:E :QDF] cds_remove_timer_from_sys_msg: 1251: gp_cds_sched_context is null
[ 1753.811210] R0: [kworker/u16:0][33944299351] [22:55:27.862551]  wlan: [6:E :QDF] cds_remove_timer_from_sys_msg: 1251: gp_cds_sched_context is null
[ 1753.811224] R0: [kworker/u16:0][33944299614] [22:55:27.862565]  wlan: [6:E :QDF] cds_remove_timer_from_sys_msg: 1251: gp_cds_sched_context is null
[ 1753.812703] R0: [kworker/u16:0][33944327992] [22:55:27.864043]  wlan: [6:E :QDF] cds_get_context: Module ID 21 context is Null
[ 1753.812715] R0: [kworker/u16:0][33944328235] [22:55:27.864056]  wlan: [6:I :HDD] hdd_wlan_stop_modules: 10508: Wlan transition (now CLOSED)
[ 1753.812725] R0: [kworker/u16:0][33944328429] [22:55:27.864066]  wlan: [6:F :HDD] hdd_wlan_stop_modules: 10515: stop WLAN module: exit driver status=3
[ 1753.812837] R0: [kworker/u16:0][33944330575] [22:55:27.864178]  wlan: [6:I :HDD] hdd_wlan_shutdown: 1502: WLAN driver shutdown complete
[ 1753.813843] wlan: re-probing driver v5.2.1.1J.1
[ 1753.813854] ipa ipa3_uc_reg_rdyCB:1719 bad parm. inout=0000000000000000 
[ 1753.813898] R0: [kworker/u16:0][33944350934] [22:55:27.865238]  wlan: [6:I :HDD] hdd_wlan_start_modules: 2164: Wlan transition (CLOSED -> OPENED)
[ 1753.814560] ipa ipa3_uc_reg_rdyCB:1719 bad parm. inout=0000000000000000 
[ 1753.867139] IPC_RTR: process_new_server_msg: Server 00001003 create rejected, version = 0
[ 1753.869716] R0: [kworker/u16:0][33945422445] [22:55:27.921046]  wlan: [6:I :HDD] hdd_napi_create: 131: napi instances were created. Map=0x602
[ 1753.869758] R0: [kworker/u16:0][33945423369] [22:55:27.921094]  wlan: [6:E :QDF] cds_get_context: Module ID 21 context is Null
[ 1753.875403] R0: [cds_mc_thread][33945531681] [22:55:27.926735]  wlan: [2368:I :QDF] cds_mc_thread: MC Thread 2368 (cds_mc_thread) starting up
[ 1753.875548] R0: [kworker/u16:0][33945534544] [22:55:27.926884]  wlan: [6:E :QDF] cds_get_context: Module ID 21 context is Null
[ 1753.876297] R0: [kworker/u16:0][33945548892] [22:55:27.927632]  wlan: [6:E :QDF] error while creating debugfs dir for WMI1\x0a
[ 1753.876352] R0: [kworker/u16:0][33945549966] [22:55:27.927688]  wlan: [6:E :QDF] ol_if_dfs_attach: called; ptr=0000000000000000, radar_info=0000000000000000\x0a
[ 1753.898712] R0: [kworker/u16:0][33945979209] [22:55:27.950044]  wlan: [6:E :QDF] Target Ready! TX resource : 2 size:2184, MaxMsgsPerHTCBundle = 1
[ 1753.898736] R0: [kworker/u16:0][33945979797] [22:55:27.950075]  wlan: [6:E :QDF] SVS Index : 1 TX : 0x100 : alloc:2
[ 1753.898754] R0: [kworker/u16:0][33945980151] [22:55:27.950093]  wlan: [6:E :QDF] SVC:0x0001, ULpipe:0 DLpipe:2 id:0 Ready
[ 1753.899286] R0: [kworker/u16:0][33945990346] [22:55:27.950624]  wlan: [6:I :HTT] full_reorder_offloaded 1
[ 1753.899302] R0: [kworker/u16:0][33945990649] [22:55:27.950640]  wlan: [6:I :HTT] ce_classify 1
[ 1753.900525] R0: [kworker/u16:0][33946014141] [22:55:27.951864]  wlan: [6:E :QDF] SVC:0x0300, ULpipe:4 DLpipe:1 id:1 Ready
[ 1753.900536] R0: [kworker/u16:0][33946014395] [22:55:27.951876]  wlan: [6:E :QDF] SVC:0x0300 ep:1 TX flow control disabled
[ 1753.900872] R0: [kworker/u16:0][33946020828] [22:55:27.952212]  wlan: [6:I :HIF] hif_map_service_to_pipe: ul pipe is NOT updated for service 769
[ 1753.900884] R0: [kworker/u16:0][33946021064] [22:55:27.952224]  wlan: [6:E :QDF] SVC:0x0301, ULpipe:0 DLpipe:9 id:2 Ready
[ 1753.900894] R0: [kworker/u16:0][33946021256] [22:55:27.952234]  wlan: [6:E :QDF] SVC:0x0301 ep:2 TX flow control disabled
[ 1753.900904] R0: [kworker/u16:0][33946021448] [22:55:27.952244]  wlan: [6:I :HIF] hif_map_service_to_pipe: ul pipe is NOT updated for service 769
[ 1753.901257] R0: [kworker/u16:0][33946028208] [22:55:27.952596]  wlan: [6:I :HIF] hif_map_service_to_pipe: ul pipe is NOT updated for service 770
[ 1753.901267] R0: [kworker/u16:0][33946028441] [22:55:27.952608]  wlan: [6:E :QDF] SVC:0x0302, ULpipe:0 DLpipe:10 id:3 Ready
[ 1753.901277] R0: [kworker/u16:0][33946028615] [22:55:27.952617]  wlan: [6:E :QDF] SVC:0x0302 ep:3 TX flow control disabled
[ 1753.901286] R0: [kworker/u16:0][33946028806] [22:55:27.952627]  wlan: [6:I :HIF] hif_map_service_to_pipe: ul pipe is NOT updated for service 770
[ 1753.901301] R0: [kworker/u16:0][33946029074] [22:55:27.952641]  wlan: [6:E :TRX] ol_txrx_debugfs_init: error while creating debugfs dir for dpt_stats
[ 1753.901572] R0: [kworker/u16:0][33946033320] [22:55:27.952862]  wlan: [6:I :HIF] hif_map_service_to_pipe: ul pipe is NOT updated for service 1536
[ 1753.901583] R0: [kworker/u16:0][33946034508] [22:55:27.952924]  wlan: [6:E :QDF] SVC:0x0600, ULpipe:0 DLpipe:11 id:4 Ready
[ 1753.901592] R0: [kworker/u16:0][33946034683] [22:55:27.952933]  wlan: [6:E :QDF] SVC:0x0600 ep:4 TX flow control disabled
[ 1753.901665] R0: [kworker/u16:0][33946036077] [22:55:27.953006]  wlan: [6:E :QDF] SVC:0x0100, ULpipe:3 DLpipe:2 id:5 Ready
[ 1753.902062] R0: [kworker/u16:0][33946043666] [22:55:27.953401]  wlan: [6:E :QDF] HTC using TX credit flow control
[ 1753.902755] R0: [cds_mc_thread][33946056991] [22:55:27.954095]  wlan: [2368:I :WMA] wma_rx_service_ready_event: Firmware build version : 120181df
[ 1753.902768] R0: [cds_mc_thread][33946057250] [22:55:27.954108]  wlan: [2368:W :WMA] wma_rx_service_ready_event: Board version is unknown!
[ 1753.902779] R0: [cds_mc_thread][33946057455] [22:55:27.954119]  wlan: [2368:I :TRX] ol_tx_set_desc_global_pool_size: 762: Global pool size: 3600\x0a
[ 1753.933651] R0: [cds_mc_thread][33946650045] [22:55:27.984983]  wlan: [2368:I :HDD] hdd_update_tgt_cfg: 1698: hw_mac is zero
[ 1753.933928] R0: [cds_mc_thread][33946655175] [22:55:27.985250]  wlan: [2368:I :HDD] hdd_update_wiphy_vhtcap: 1086: Updated wiphy vhtcap:0x3917bb2, CSNAntSupp:3, NumSoundDim:1
[ 1753.933953] R0: [cds_mc_thread][33946655908] [22:55:27.985289]  wlan: [2368:I :HDD] hdd_nan_datapath_target_config: 109: enable_nan_datapath: 1
[ 1753.964575] R0: [kworker/u16:0][33947243784] [22:55:28.015908]  wlan: [6:I :HTT] HTT: full reorder offload enabled
[ 1753.982501] R0: [kworker/u16:0][33947587976] [22:55:28.033834]  wlan: [6:I :HDD] hdd_wlan_start_modules: 2231: Wlan transition (now OPENED)
[ 1753.982520] Host SW:5.2.1.1J.1, FW:1.2.0.479.2, HW:WCN3990_V2.1
[ 1753.982542] R0: [kworker/u16:0][33947588913] [22:55:28.033883]  wlan: [6:I :HDD] hdd_wlan_start_modules: 2254: Wlan transition (OPENED -> ENABLED)
[ 1753.987428] R0: [kworker/u16:0][33947682689] [22:55:28.038767]  wlan: [6:I :HDD] hdd_ipa_uc_ol_init:3215: CONS DB pipe out 0x1e720c8 TX PIPE Handle 0x19
[ 1753.990746] R0: [kworker/u16:0][33947746402] [22:55:28.042085]  wlan: [6:I :HDD] hdd_ipa_uc_ol_init:3311: PROD DB pipe out 0x1e720c0 RX PIPE Handle 0xa
[ 1753.990810] R0: [kworker/u16:0][33947747658] [22:55:28.042151]  wlan: [6:I :QDF] cds_enable: wma correctly started
[ 1753.990943] R0: [kworker/u16:0][33947750208] [22:55:28.042283]  wlan: [6:I :SYS] Creating periodic timer for OLBC UPDATE CACHE TIMEOUT\x0a
[ 1753.990973] R0: [kworker/u16:0][33947750785] [22:55:28.042313]  wlan: [6:I :QDF] cds_enable: MAC correctly started
[ 1753.990988] R0: [cds_mc_thread][33947751077] [22:55:28.042329]  wlan: [2368:E :WMA] Unhandled WMA message of type 4165
[ 1753.991077] R0: [kworker/u16:0][33947752793] [22:55:28.042418]  wlan: [6:I :QDF] cds_enable: SME correctly started
[ 1753.991109] R0: [kworker/u16:0][33947753384] [22:55:28.042449]  wlan: [6:I :HTT] Receive flow steering configuration, disable gEnableFlowSteering(=0) in ini if FW doesnot support it\x0a
[ 1753.991123] R0: [kworker/u16:0][33947753660] [22:55:28.042463]  wlan: [6:I :HTT] Enable Rx flow steering
[ 1753.991131] R0: [kworker/u16:0][33947753833] [22:55:28.042472]  wlan: [6:I :HTT] Updated maxMSDUsPerRxInd
[ 1753.991140] R0: [kworker/u16:0][33947754001] [22:55:28.042481]  wlan: [6:I :HTT] htt_h2t_rx_ring_rfs_cfg_msg_ll: Sending msg_word: 0x0008010f
[ 1753.991144] R0: [soft_irq][33947754076] [22:55:28.042485]  wlan: [0:I :HTT] target uses HTT version 3.48; host uses 3.50
[ 1753.991149] R0: [soft_irq][33947754184] [22:55:28.042490]  wlan: [0:W :HTT] *** Warning: host/target HTT versions are 
[ 1753.991158] R0: [soft_irq][33947754350] [22:55:28.042499]  wlan: [0:W :HTT]  different, though compatible!
[ 1753.991160] R0: [kworker/u16:0][33947754364] [22:55:28.042500]  wlan: [6:I :HTT] htt_h2t_rx_ring_cfg_msg_ll : 503 Pkt log is enabled\x0a
[ 1753.991174] R0: [kworker/u16:0][33947754655] [22:55:28.042515]  wlan: [6:I :QDF] cds_enable: CDS Start is successful!!
[ 1753.991237] R0: [cds_mc_thread][33947755864] [22:55:28.042578]  wlan: [2368:E :WMA] Unhandled WMA message of type 4197
[ 1753.995214] R0: [kworker/u16:0][33947832175] [22:55:28.046553]  wlan: [6:W :HDD] hdd_features_init: 10066: Unable to send DBS scan selection setting to FW
[ 1753.995279] R0: [kworker/u16:0][33947833474] [22:55:28.046620]  wlan: [6:W :SME] dump_csr_command_info: 515: Unhandled command: 524292 session: 0
[ 1753.995361] R0: [kworker/u16:0][33947835040] [22:55:28.046702]  wlan: [6:I :HDD] hdd_wlan_start_modules: 2271: Driver Modules Successfully Enabled
[ 1753.995373] Host SW:5.2.1.1J.1, FW:1.2.0.479.2, HW:WCN3990_V2.1
[ 1753.995445] R0: [kworker/u16:0][33947836660] [22:55:28.046786]  wlan: [6:W :SME] dump_csr_command_info: 515: Unhandled command: 524292 session: 0
[ 1753.995793] R0: [cds_mc_thread][33947843331] [22:55:28.047134]  wlan: [2368:I :WMI] send_pdev_set_dual_mac_config_cmd_tlv: scan_config:0 fw_mode_config:0
[ 1753.997531] R0: [cds_mc_thread][33947876696] [22:55:28.048871]  wlan: [2368:W :SME] dump_csr_command_info: 515: Unhandled command: 65541 session: 0
[ 1753.998047] R0: [cds_mc_thread][33947886610] [22:55:28.049388]  wlan: [2368:E :WMA] unknown type 2 subtype 0
[ 1753.998345] R0: [kworker/u16:0][33947892337] [22:55:28.049686]  wlan: [6:I :HDD] hdd_init_station_mode: 3340: send HT/VHT IE per band using nondbs hwmode
[ 1753.998454] R0: [cds_mc_thread][33947894426] [22:55:28.049795]  wlan: [2368:E :WMA] Invalid wma_cli_set vdev command/Not yet implemented 0x81
[ 1753.998481] R0: [kworker/u16:0][33947894937] [22:55:28.049821]  wlan: [6:E :HDD] hdd_init_station_mode: 3406: LRO is disabled either because of kernel doesnot support or disabled in INI or via vendor commandi. err code -38
[ 1753.999387] R0: [kworker/u16:0][33947912309] [22:55:28.050726]  wlan: [6:W :SME] dump_csr_command_info: 515: Unhandled command: 65541 session: 1
[ 1753.999855] R0: [cds_mc_thread][33947921309] [22:55:28.051195]  wlan: [2368:E :WMA] unknown type 1 subtype 1
[ 1754.000315] R0: [kworker/u16:0][33947930138] [22:55:28.051655]  wlan: [6:I :HDD] hdd_init_station_mode: 3340: send HT/VHT IE per band using nondbs hwmode
[ 1754.000439] R0: [kworker/u16:0][33947932529] [22:55:28.051779]  wlan: [6:E :HDD] hdd_init_station_mode: 3406: LRO is disabled either because of kernel doesnot support or disabled in INI or via vendor commandi. err code -38
[ 1754.000840] R0: [kworker/u16:0][33947940181] [22:55:28.052178]  wlan: [6:I :HDD] hdd_wlan_re_init: 1636: WLAN host driver reinitiation completed!

**Comment by nathanchance** [comment] 2018-08-19 03:22
Several things:

1. Why are you enabling module support? All of the kernel drivers are built in.

2. Define unstable. According to the log, the Wi-Fi driver is unloaded itself.

3. As soon as you start modifying stuff, you're on your own. I only verify things are working with my configuration.

Furthermore, my device is out for an RMA so I can't reproduce this even if I wanted to. Closing because it's not related to the kernel binary I seed out.

**Closed as completed by nathanchance** 2018-08-19 03:22 UTC
